class Translator:
    """
    A simple translation utility for a Streamlit app.
    """
    def __init__(self):
        self.translations = {
             "English": {
                "title": "Product Sales Dashboard",
                "filter": "Filter Data",
                "average_price": "Average Price",
                "average_margin": "Average Margin",
                "select_sku": "Select SKU",
                "overview_tab": "Overview",
                "analysis_tab": "Detailed Analysis",
                "data_view_tab": "Data View",
                "sales_over_time": "Sales Over Time",
                "margin_analysis": "Margin Analysis",
                "top_selling_products": "Top Selling Products",
                "data_table": "Data Table",
                "download_csv": "Download data as CSV",
                "show_summary": "Show Summary Statistics",
                "upload_prompt": "Drag and Drop or Click to Upload a CSV file",
                "please_upload": "Please upload a CSV file to view the dashboard.",
                "sales_over_sku": "Sales Over SKU",
                "correlation_analysis": "Price-Quantity Correlation",
                "quantity": "Quantity",
                "sku": "SKU",
                "total_sales": "Total Sales",
                "data_error": "The uploaded data is invalid. Please check the file and try again.",
                "total_profit": "Total Profit",
                "total_items_sold": "Total Items Sold",
                "unit_price_distribution": "Unit Price Distribution",
                "profit_margin_by_sku": "Profit Margin by SKU",
                "process_error": "An error occurred while processing the uploaded file. Please check the file and try again.",

            },
            "Français": {
                "title": "Tableau de Bord des Ventes de Produits",
                "filter": "Filtrer les Données",
                "average_price": "Prix Moyen",
                "average_margin": "Marge Moyenne",
                "select_sku": "Sélectionner le SKU",
                "overview_tab": "Aperçu",
                "analysis_tab": "Analyse Détaillée",
                "data_view_tab": "Vue des Données",
                "sales_over_time": "Ventes au Fil du Temps",
                "margin_analysis": "Analyse de la Marge",
                "top_selling_products": "Produits les Plus Vendus",
                "data_table": "Tableau de Données",
                "download_csv": "Télécharger les données en CSV",
                "show_summary": "Afficher les Statistiques Résumées",
                "upload_prompt": "Faites glisser et déposez ou cliquez pour télécharger un fichier CSV",
                "please_upload": "Veuillez télécharger un fichier CSV pour afficher le tableau de bord.",
                "sales_over_sku": "Ventes par SKU",
                "correlation_analysis": "Corrélation Prix-Quantité",
                "quantity": "Quantité",
                "sku": "SKU",
                "total_sales": "Ventes Totales",
                "data_error": "Les données téléchargées ne sont pas valides. Veuillez vérifier le fichier et réessayer.",
                "total_profit": "Profit Total",
                "total_items_sold": "Articles Vendus",
                "unit_price_distribution": "Distribution des Prix Unitaire",
                "profit_margin_by_sku": "Marge de Profit par SKU",
                "process_error": "Une erreur s'est produite lors du traitement du fichier téléchargé. Veuillez vérifier le fichier et réessayer.",
            },
            "العربية": {
                "title": "لوحة مبيعات المنتجات",
                "filter": "تصفية البيانات",
                "average_price": "متوسط السعر",
                "average_margin": "متوسط الهامش",
                "select_sku": "اختر الرقم التسلسلي",
                "overview_tab": "نظرة عامة",
                "analysis_tab": "تحليل مفصل",
                "data_view_tab": "عرض البيانات",
                "sales_over_time": "المبيعات على مر الزمن",
                "margin_analysis": "تحليل الهامش",
                "top_selling_products": "المنتجات الأكثر مبيعا",
                "data_table": "جدول البيانات",
                "download_csv": "تحميل البيانات بصيغة CSV",
                "show_summary": "عرض الإحصائيات الخلاصة",
                "upload_prompt": "قم بسحب وإفلات أو انقر لتحميل ملف CSV",
                "please_upload": "يرجى تحميل ملف CSV لعرض لوحة المعلومات.",
                "sales_over_sku": "المبيعات على مر الزمن",
                "correlation_analysis": "الترابط بين السعر والكمية",
                "quantity": "الكمية",
                "sku": "الرقم التسلسلي",
                "total_sales": "إجمالي المبيعات",
                "data_error": "البيانات التي تم تحميلها غير صالحة. يرجى التحقق من الملف والمحاولة مرة أخرى.",
                "total_profit": "إجمالي الربح",
                "total_items_sold": "إجمالي العناصر المباعة",
                "unit_price_distribution": "توزيع سعر الوحدة",
                "profit_margin_by_sku": "هامش الربح حسب الرقم التسلسلي",
                "process_error": "حدث خطأ أثناء معالجة الملف المحمل. يرجى التحقق من الملف والمحاولة مرة أخرى.",
            },
            "ⵜⴰⵎⴰⵣⵉⵖⵜ": {
                "title": "ⵜⴰⴽⵡⵉⵍⵜ ⵏ ⵜⵓⴳⴳⴰⵔⴰ ⵏ ⵉⵎⴰⵍⵢⴰⵏ",
                "filter": "ⴰⵣⵔⵣⵉ ⵏ ⵜⵓⵙⴷⴰⵜ",
                "average_price": "ⵜⴰⵎⵓⵍⵜ ⵏ ⵜⴰⵙⴰⵖⵜ",
                "average_margin": "ⵜⴰⵎⵓⵍⵜ ⵏ ⵜⴰⴳⴻⵔⵎⵜ",
                "select_sku": "ⴰⴼⴰⵏ ⵏ ⵙⴽⵓ",
                "overview_tab": "ⵜⴰⵏⵎⵉⵔⵜ",
                "analysis_tab": "ⵜⴰⵏⵎⵉⵔⵜ ⵏ ⵜⴰⵎⴰⵡⴰⵙⵜ",
                "data_view_tab": "ⴰⵙⴰⵡⴰⵏ ⵏ ⵉⵎⴰⵍⵢⴰⵏ",
                "sales_over_time": "ⵜⴰⵎⵓⵍⵜ ⵏ ⵉⵎⴰⵍⵢⴰⵏ ⵏ ⵜⵓⴳⴳⴰⵔⴰ",
                "margin_analysis": "ⵜⴰⵏⵎⵉⵔⵜ ⵏ ⵜⴰⴳⴻⵔⵎⵜ",
                "top_selling_products": "ⵉⵎⴰⵍⵢⴰⵏ ⵏ ⵜⵓⴳⴳⴰⵔⴰ ⵏ ⵜⴰⵡⵓⵔⵉ",
                "data_table": "ⵜⴰⴽⵡⵉⵍⵜ ⵏ ⵉⵎⴰⵍⵢⴰⵏ",
                "download_csv": "ⴰⵣⴳⴰⵔⵡⴰ ⵏ ⵉⵎⴰⵍⵢⴰⵏ ⴳ ⴰⴱⴱⴰⵡⵏ ⵏ ⵙⵉⵙⵡⴰⵖⵜ",
                "show_summary": "ⴰⵙⵏⵓⵔⵓ ⵏ ⵜⵓⴳⴳⴰⵔⴰ ⵏ ⵉⵎⴰⵍⵢⴰⵏ",
                "upload_prompt": "ⵜⴰⴳⴷⵓⴷ ⵏ ⵉⵎⴰⵍⵢⴰⵏ ⵏ ⵙⵉⵙⵡⴰⵖⵜ ⵏ ⵉⵎⴰⵍⵢⴰⵏ ⵏ ⵜⵓⴳⴳⴰⵔⴰ ⵏ ⵉⵎⴰⵍⵢⴰⵏ", 
                "please_upload": "ⵓⵔⴰ ⵜⵉⵍⵉⵙⵉ ⵏ ⵉⵎⴰⵍⵢⴰⵏ ⵏ ⵜⵓⴳⴳⴰⵔⴰ ⵏ ⵉⵎⴰⵍⵢⴰⵏ ⵏ ⵜⵓⴳⴳⴰⵔⴰ ⵏ ⵉⵎⴰⵍⵢⴰⵏ.",
                "sales_over_sku": "ⵜⴰⵎⵓⵍⵜ ⵏ ⵙⴽⵓ",
                "correlation_analysis": "ⵜⴰⵏⵎⵉⵔⵜ ⵏ ⵜⴰⵙⴰⵖⵜ ⵏ ⵜⴰⴳⴻⵔⵎⵜ",
                "quantity": "ⵜⴰⵙⵉⵏⵏⴰ",
                "sku": "ⵙⴽⵓ",
                "total_sales": "ⵜⴰⵎⵓⵍⵜ ⵏ ⵜⵓⴳⴳⴰⵔⴰ",
                "data_error": "ⵉⵎⴰⵍⵢⴰⵏ ⵏ ⵜⵓⴳⴳⴰⵔⴰ ⵏ ⵉⵎⴰⵍⵢⴰⵏ ⴰⵙⵏⵓⵔⵓ. ⵉⵍⵍⴰ ⵜⴰⵎⵓⵍⵜ ⵏ ⵜⵓⴳⴳⴰⵔⴰ ⵏ ⵉⵎⴰⵍⵢⴰⵏ ⵏ ⵜⵓⴳⴳⴰⵔⴰ ⵏ ⵉⵎⴰⵍⵢⴰⵏ.",
                "total_profit": "ⵜⴰⵎⵓⵍⵜ ⵏ ⵜⴰⴳⴻⵔⵎⵜ",
                "total_items_sold": "ⵜⴰⵎⵓⵍⵜ ⵏ ⵜⵓⴳⴳⴰⵔⴰ",
                "unit_price_distribution": "ⵜⵓⵙⵉⵏⵏⴰ ⵏ ⵜⴰⵙⴰⵖⵜ ⵏ ⵜⵓⵙⵉⵏⵏⴰⵏ",
                "profit_margin_by_sku": "ⵜⴰⴳⴻⵔⵎⵜ ⵏ ⵜⴰⴳⴻⵔⵎⵜ ⵏ ⵜⵓⴳⴳⴰⵔⴰ",
                "process_error": "ⴰⵙⵏⵓⵔⵓ ⵏ ⵉⵎⴰⵍⵢⴰⵏ ⵏ ⵜⵓⴳⴳⴰⵔⴰ ⵏ ⵉⵎⴰⵍⵢⴰⵏ ⴰⵙⵏⵓⵔⵓ. ⵉⵍⵍⴰ ⵜⴰⵎⵓⵍⵜ ⵏ ⵜⵓⴳⴳⴰⵔⴰ ⵏ ⵉⵎⴰⵍⵢⴰⵏ ⵏ ⵜⵓⴳⴳⴰⵔⴰ ⵏ ⵉⵎⴰⵍⵢⴰⵏ.",
            },
            "Tamazight": {
                "title": "Takwil2t n Tuggara n Ima9yan",
                "filter": "Azrzi n Tusda2t",
                "average_price": "Tamul2t n Tasag9t",
                "average_margin": "Tamul2t n Tagermt",
                "select_sku": "Afan n SKU",
                "overview_tab": "Tanmirt",
                "analysis_tab": "Tanmirt n Tamawast",
                "data_view_tab": "Asawan n Imalyan",
                "sales_over_time": "Tamul2t n Imalyan n Tuggara",
                "margin_analysis": "Tanmirt n Tagermt",
                "top_selling_products": "Imalyan n Tuggara n Tawuri",
                "data_table": "Takwil2t n Imalyan",
                "download_csv": "Azgarwa n Imalyan g Abbawn n Siswa9t",
                "show_summary": "Asnuru n Tuggara n Imalyan",
                "upload_prompt": "Tagdud n Imalyan n Siswa9t n Imalyan n Tuggara n Imalyan",
                "please_upload": "Ura Tilisi n Imalyan n Tuggara n Imalyan n Tuggara n Imalyan.",
                "sales_over_sku": "Tamul2t n SKU",
                "correlation_analysis": "Tanmirt n Tasag9t n Tagermt",
                "quantity": "Tasinnna",
                "sku": "SKU",
                "total_sales": "Tamul2t n Tuggara",
                "data_error": "Imalyan n Tuggara n Imalyan Asnuru. Illa Tamul2t n Tuggara n Imalyan n Tuggara n Imalyan.",
                "total_profit": "Tamul2t n Tagermt",
                "total_items_sold": "Tamul2t n Tuggara",
                "unit_price_distribution": "Tawzint n Tasag9t n Tagermt",
                "profit_margin_by_sku": "Tamul2t n Tagermt n SKU",
                "process_error": "Asnuru n Imalyan n Tuggara n Imalyan Asnuru. Illa Tamul2t n Tuggara n Imalyan n Tuggara n Imalyan.",
            },
            "تمازيغت": {
                "title": "تاكويلت ن توݣݣارا ن إماليان",
                "filter": "أزرزي ن توسدات",
                "average_price": "تامولت ن تاساغت",
                "average_margin": "تامولت ن تاݣرمت",
                "select_sku": "أفان ن سكو",
                "overview_tab": "تانميرت",
                "analysis_tab": "تانميرت ن تاماواست",
                "data_view_tab": "أساوان ن إماليان",
                "sales_over_time": "تامولت ن إماليان ن توݣݣارا",
                "margin_analysis": "تانميرت ن تاݣرمت",
                "top_selling_products": "إماليان ن توݣݣارا ن تاوري",
                "data_table": "تاكويلت ن إماليان",
                "download_csv": "أزݣاروا ن إماليان ݣ أباون ن سيسواغت",
                "show_summary": "أسنورو ن توݣݣارا ن إماليان",
                "upload_prompt": "تاݣدود ن إماليان ن سيسواغت ن إماليان ن توݣݣارا ن إماليان",
                "please_upload": "ورا تيليسي ن إماليان ن توݣݣارا ن إماليان ن توݣݣارا ن إماليان.",
                "sales_over_sku": "تامولت ن سكو",
                "correlation_analysis": "تانميرت ن تاساغت ن تاݣرمت",
                "quantity": "تاسينا",
                "sku": "سكو",
                "total_sales": "تامولت ن توݣݣارا",
                "data_error": "إماليان ن توݣݣارا ن إماليان أسنورو. إيلا تامولت ن توݣݣارا ن إماليان ن توݣݣارا ن إماليان.",
                "total_profit": "تامولت ن تاݣرمت",
                "total_items_sold": "تامولت ن توݣݣارا",
                "unit_price_distribution": "تاوزينت ن تاساغت ن تاݣرمت",
                "profit_margin_by_sku": "تامولت ن تاݣرمت ن سكو",
                "process_error": "أسنورو ن إماليان ن توݣݣارا ن إماليان أسنورو. إيلا تامولت ن توݣݣارا ن إماليان ن توݣݣارا ن إماليان.",
            }
        }

    def get_translation(self, language, key):
        """
        Retrieves a translation based on the specified language and key.

        Parameters:
        - language: The language to translate into.
        - key: The key for the translation term.

        Returns:
        - The translated string if available, otherwise the key itself.
        """
        return self.translations.get(language, {}).get(key, key)

# Usage example
# translator = Translator()
# text = translator.get_translation("Français", "title")
